---
- name: Setup Postgres
  include: postgres.yml
- name: Setup Redis
  include: redis.yml
- name: Setup Pacifica
  import_role:
    name: pacifica.ansible_pacifica
- name: Load Metadata
  include: load-metadata.yml
